/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prvisual.controllaboratorios;

import control.ctr_Usuario;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author SAID
 */
public class Nuevo_usuario extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Nuevo_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_apellidou = new javax.swing.JTextField();
        txt_nombreu = new javax.swing.JTextField();
        lblnombreusuario = new javax.swing.JLabel();
        lblapellidousuario = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        txt_usuariou = new javax.swing.JTextField();
        pswusuario = new javax.swing.JPasswordField();
        lblpasswordusuario = new javax.swing.JLabel();
        lbltelefonousuario = new javax.swing.JLabel();
        txt_rol = new javax.swing.JTextField();
        btn_guardarU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombreusuario.setText("Nombre");

        lblapellidousuario.setText("Apellido");

        lblusuario.setText("Usuario/cedula");

        txt_usuariou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuariouActionPerformed(evt);
            }
        });

        pswusuario.setPreferredSize(new java.awt.Dimension(162, 23));

        lblpasswordusuario.setText("Password");

        lbltelefonousuario.setText("Rol");

        txt_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rolActionPerformed(evt);
            }
        });

        btn_guardarU.setText("Guardar");
        btn_guardarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblusuario)
                        .addGap(53, 53, 53)
                        .addComponent(txt_usuariou, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 59, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblnombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(txt_nombreu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblapellidousuario)
                            .addGap(54, 54, 54)
                            .addComponent(txt_apellidou, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblpasswordusuario)
                            .addGap(50, 50, 50)
                            .addComponent(pswusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbltelefonousuario)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(btn_guardarU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 100, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuariou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuario))
                .addGap(84, 84, 84)
                .addComponent(txt_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 69, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblnombreusuario))
                        .addComponent(txt_nombreu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblapellidousuario)
                        .addComponent(txt_apellidou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(78, 78, 78)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblpasswordusuario)
                        .addComponent(pswusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(lbltelefonousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(57, 57, 57)
                    .addComponent(btn_guardarU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 69, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuariouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuariouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuariouActionPerformed

    private void txt_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rolActionPerformed

    private void btn_guardarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarUActionPerformed

        if (txt_nombreu.getText().isEmpty()|| txt_apellidou.getText().isEmpty() || txt_usuariou.getText().isEmpty()
            || pswusuario.getText().isEmpty() || txt_rol.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los Campos");
        } else {
            //validamos si el usuario ya existe

            Usuario usuario=new Usuario();
            ctr_Usuario controlusuario=new ctr_Usuario();

            if (!controlusuario.existeUsuario(txt_usuariou.getText().trim())) {

                usuario.setNombre(txt_nombreu.getText().trim());
                usuario.setApellido(txt_apellidou.getText().trim());
                usuario.setUsuario(txt_usuariou.getText().trim());
                usuario.setPassword(pswusuario.getText().trim());
                usuario.setRol(txt_rol.getText().trim());

                if (controlusuario.guardar(usuario)) {
                    JOptionPane.showMessageDialog(null, "Usuario Registrado");
                    Limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar Usuario");
                }
            } else {

                JOptionPane.showMessageDialog(null, "Ya existe este Usuario");

                limpiarusuario();
            }
        }

    }//GEN-LAST:event_btn_guardarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarU;
    private javax.swing.JLabel lblapellidousuario;
    private javax.swing.JLabel lblnombreusuario;
    private javax.swing.JLabel lblpasswordusuario;
    private javax.swing.JLabel lbltelefonousuario;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField pswusuario;
    private javax.swing.JTextField txt_apellidou;
    private javax.swing.JTextField txt_nombreu;
    private javax.swing.JTextField txt_rol;
    private javax.swing.JTextField txt_usuariou;
    // End of variables declaration//GEN-END:variables

private void Limpiar(){
txt_nombreu.setText("");
txt_apellidou.setText("");
txt_usuariou.setText("");
pswusuario.setText("");
txt_rol.setText("");


}
private void limpiarusuario(){
txt_usuariou.setText("");

}

}
