/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prvisual.controllaboratorios;

import control.ctr_Usuario;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author SAID
 */
public class Nuevo_usuario extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Nuevo_usuario() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_guardarU = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblnombreusuario4 = new javax.swing.JLabel();
        pswusuario = new javax.swing.JPasswordField();
        lblnombreusuario2 = new javax.swing.JLabel();
        txt_usuariou = new javax.swing.JTextField();
        lblnombreusuario3 = new javax.swing.JLabel();
        txt_apellidou = new javax.swing.JTextField();
        lblnombreusuario1 = new javax.swing.JLabel();
        lblnombreusuario = new javax.swing.JLabel();
        txt_nombreu = new javax.swing.JTextField();
        cbx_rol = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setText("Resgistros de Credenciales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 14, 265, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 450));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 10, 450));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 410, 10));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setEnabled(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guardarU.setBackground(new java.awt.Color(51, 153, 255));
        btn_guardarU.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btn_guardarU.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarU.setText("Guardar");
        btn_guardarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarUActionPerformed(evt);
            }
        });
        jPanel5.add(btn_guardarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 171, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 0, -1, -1));

        lblnombreusuario4.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblnombreusuario4.setText("Rol");
        jPanel5.add(lblnombreusuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        pswusuario.setPreferredSize(new java.awt.Dimension(162, 23));
        jPanel5.add(pswusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 233, -1, -1));

        lblnombreusuario2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblnombreusuario2.setText("Contraseña");
        jPanel5.add(lblnombreusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 233, -1, -1));

        txt_usuariou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuariouActionPerformed(evt);
            }
        });
        jPanel5.add(txt_usuariou, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 173, 162, -1));

        lblnombreusuario3.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblnombreusuario3.setText("Usuario/cedula");
        jPanel5.add(lblnombreusuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 173, -1, -1));
        jPanel5.add(txt_apellidou, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 121, 162, -1));

        lblnombreusuario1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblnombreusuario1.setText("Apellido");
        jPanel5.add(lblnombreusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 121, 71, -1));

        lblnombreusuario.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblnombreusuario.setText("Nombre");
        jPanel5.add(lblnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 66, 71, -1));
        jPanel5.add(txt_nombreu, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 66, 162, -1));

        cbx_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingrese Rol :", "Estudiante", "Docente" }));
        jPanel5.add(cbx_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 288, 162, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuariouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuariouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuariouActionPerformed

    private void btn_guardarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarUActionPerformed

        if (txt_nombreu.getText().isEmpty()|| txt_apellidou.getText().isEmpty() || txt_usuariou.getText().isEmpty()
            || pswusuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los Campos");
        } else {
            //validamos si el usuario ya existe

            Usuario usuario=new Usuario();
            ctr_Usuario controlusuario=new ctr_Usuario();

            if (!controlusuario.existeUsuario(txt_usuariou.getText().trim())) {

                usuario.setNombre(txt_nombreu.getText().trim());
                usuario.setApellido(txt_apellidou.getText().trim());
                usuario.setUsuario(txt_usuariou.getText().trim());
                usuario.setPassword(pswusuario.getText().trim());
                usuario.setRol(cbx_rol.getSelectedItem().toString());

                if (controlusuario.guardar(usuario)) {
                    JOptionPane.showMessageDialog(null, "Usuario Registrado");
                    Limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar Usuario");
                }
            } else {

                JOptionPane.showMessageDialog(null, "Ya existe este Usuario");

                limpiarusuario();
            }
        }

    }//GEN-LAST:event_btn_guardarUActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarU;
    private javax.swing.JComboBox<String> cbx_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblnombreusuario;
    private javax.swing.JLabel lblnombreusuario1;
    private javax.swing.JLabel lblnombreusuario2;
    private javax.swing.JLabel lblnombreusuario3;
    private javax.swing.JLabel lblnombreusuario4;
    private javax.swing.JPasswordField pswusuario;
    private javax.swing.JTextField txt_apellidou;
    private javax.swing.JTextField txt_nombreu;
    private javax.swing.JTextField txt_usuariou;
    // End of variables declaration//GEN-END:variables

private void Limpiar(){
txt_nombreu.setText("");
txt_apellidou.setText("");
txt_usuariou.setText("");
pswusuario.setText("");
cbx_rol.setActionCommand("");


}
private void limpiarusuario(){
txt_usuariou.setText("");

}

}
