/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import atributosYmetodos.horario;
import conecxion.conMysql;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jefferson
 */
public final class admFuncional extends javax.swing.JFrame {

    Map<String, String> labMap = new HashMap<>();

    /**
     * Creates new form HORARIOS
     */
    public admFuncional() throws ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        cargarDatos();
      
            MOSTRAR_HORARIOS();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtHorafin = new javax.swing.JTextField();
        txtHoraini = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblaconH = new javax.swing.JTable();
        btn_modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbxlab = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDocente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel1.setText("MATERIA :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel2.setText("HORA DE SALIDA : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel3.setText("DIA :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel4.setText("LABORATORIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel5.setText("HORA DE INICIO :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, -1));
        jPanel1.add(txtHorafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 100, -1));
        jPanel1.add(txtHoraini, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, -1));
        jPanel1.add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblaconH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblaconH.setGridColor(new java.awt.Color(255, 255, 255));
        tblaconH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblaconHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblaconH);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 820, 150));

        btn_modificar.setBackground(new java.awt.Color(51, 153, 255));
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("BUSCAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ELIMINAR");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("AGREGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jPanel1.add(cbxlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 110, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, 50));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel6.setText("DOCENTE: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));
        jPanel1.add(txtDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar
        horario hr = new horario();
        String nombreSeleccionado = cbxlab.getSelectedItem().toString();
        String idSeleccionado = labMap.get(nombreSeleccionado);
        hr.setMateria(txtMateria.getText());
        hr.setDia_semana(txtDia.getText());
        hr.setHora_inicio(txtHoraini.getText());
        hr.setHora_fin(txtHorafin.getText());
        hr.setLaboratorio(idSeleccionado);
        hr.setDocente(txtDocente.getText());
        hr.registrar_horario();
        try {
            MOSTRAR_HORARIOS();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admFuncional.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar_horario();

    }//GEN-LAST:event_agregar

    private void tblaconHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblaconHMouseClicked
        txtMateria.setText(tblaconH.getValueAt(tblaconH.getSelectedRow(), 0).toString());
        txtHoraini.setText(tblaconH.getValueAt(tblaconH.getSelectedRow(), 1).toString());
        txtHorafin.setText(tblaconH.getValueAt(tblaconH.getSelectedRow(), 2).toString());
        txtDia.setText(tblaconH.getValueAt(tblaconH.getSelectedRow(), 3).toString());
        txtDocente.setText(tblaconH.getValueAt(tblaconH.getSelectedRow(), 5).toString());
 
    }//GEN-LAST:event_tblaconHMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void cargarDatos() {
        // Conectar a la base de datos
        conMysql c1 = new conMysql();
        try {
            // Obtener las marcas
            String query = "SELECT nombre,idLaboratorio FROM acceso_lab.laboratorios;";
            ResultSet resultSet = c1.EjecutaSql(query);

            while (resultSet.next()) {
                String id = resultSet.getString("idLaboratorio");

                String nombre = resultSet.getString("nombre");
                cbxlab.addItem(nombre);
               labMap.put(nombre, id);
            }
        } catch (SQLException e) {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admFuncional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        public void MOSTRAR_HORARIOS() throws ClassNotFoundException {

            String sql = ("SELECT  materia,hora_inicio,hora_fin,dia_semana,nombre,docente FROM tb_horarios,laboratorios where tb_horarios.idLaboratorio=laboratorios.idLaboratorio;");
            System.out.println("648" + sql);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("MATERIA");
            modelo.addColumn("HORA DE INICIO");
            modelo.addColumn("HORA DE SALIDA");
            modelo.addColumn("DIA");
            modelo.addColumn("LABORATORIO");
            modelo.addColumn("DOCENTE");
            tblaconH.setModel(modelo);
            String[] datos = new String[6];
            try {
                conMysql c1 = new conMysql();
                try (ResultSet res = c1.EjecutaSql(sql)) {
                    while (res.next()) {
                        datos[0] = res.getString(1);
                        datos[1] = res.getString(2);
                        datos[2] = res.getString(3);
                        datos[3] = res.getString(4);
                        datos[4] = res.getString(5);
                         datos[5] = res.getString(6);
                        modelo.addRow(datos);

                    }
                }
                tblaconH.setModel(modelo);

            } catch (SQLException e) {
                JOptionPane.showInternalMessageDialog(null, "error" + e.toString());
            }
        }
    
    public void limpiar_horario(){
        txtDia.setText("");
        txtDocente.setText("");
        txtHorafin.setText("");
        txtHoraini.setText("");
        txtMateria.setText("");
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new admFuncional().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(admFuncional.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cbxlab;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblaconH;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDocente;
    private javax.swing.JTextField txtHorafin;
    private javax.swing.JTextField txtHoraini;
    private javax.swing.JTextField txtMateria;
    // End of variables declaration//GEN-END:variables
}
